# Ruff configuration
line-length = 120
target-version = "py313"

[lint]
# Enable recommended rules
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "PT",  # flake8-pytest-style
]

# Ignore specific rules in test files
[lint.per-file-ignores]
"tests/**/*.py" = [
    "F841",    # Local variable assigned but never used (pytest fixtures)
    "ARG001",  # Unused function argument (pytest fixtures)
    "ARG002",  # Unused method argument
    "C416",    # Unnecessary list comprehension (list() is less readable in tests)
    "UP043",   # Unnecessary default type arguments (explicit is better in tests)
]
"src/birkenbihl/gui/**/*.py" = [
    "N802",    # Function name should be lowercase (Qt methods use camelCase)
]

[format]
quote-style = "double"
indent-style = "space"
