"""UI constants for the Birkenbihl application."""

# Supported languages (ISO 639-1 codes) - European languages first, then others alphabetically
LANGUAGES = {
    # European languages (alphabetically by German name)
    "bg": "Bulgarisch",
    "da": "Dänisch",
    "de": "Deutsch",
    "en": "Englisch",
    "et": "Estnisch",
    "fi": "Finnisch",
    "fr": "Französisch",
    "el": "Griechisch",
    "it": "Italienisch",
    "hr": "Kroatisch",
    "lv": "Lettisch",
    "lt": "Litauisch",
    "nl": "Niederländisch",
    "no": "Norwegisch",
    "pl": "Polnisch",
    "pt": "Portugiesisch",
    "ro": "Rumänisch",
    "ru": "Russisch",
    "sv": "Schwedisch",
    "sk": "Slowakisch",
    "sl": "Slowenisch",
    "es": "Spanisch",
    "cs": "Tschechisch",
    "tr": "Türkisch",
    "uk": "Ukrainisch",
    "hu": "Ungarisch",
    # Non-European languages (alphabetically by German name)
    "ar": "Arabisch",
    "zh": "Chinesisch",
    "he": "Hebräisch",
    "hi": "Hindi",
    "id": "Indonesisch",
    "ja": "Japanisch",
    "ko": "Koreanisch",
    "fa": "Persisch",
    "th": "Thailändisch",
    "vi": "Vietnamesisch",
}
